### ISSUE TITLE
statefulset中mysql 复制 Slave_IO_Running 一直处于Connecting状态

### ISSUE THREAD

**Issue by shenkonghui** [shenkonghui/issue#106]
```
mysql> show slave status\G;
*************************** 1. row ***************************
               Slave_IO_State: Connecting to master
                  Master_Host: mysql-test-0.mysql-test-headless
                  Master_User: replic
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File:
          Read_Master_Log_Pos: 4
               Relay_Log_File: relay.000001
                Relay_Log_Pos: 4
        Relay_Master_Log_File:
             Slave_IO_Running: Connecting
```

mysql复制是通过headlessservice 进行连接的，发现 telnet  域名很慢(大概 需要1、2秒时间)， ip很快，所以是dns的问题

手动将hosts中加上域名就正常了

hosts默认是只有pod 和 带集群完整的域名，没有 pod.headlessservice. 在其他集群是一切正常没有延迟

```
10.244.214.77	mysql-test-0.mysql-test-headless.shenkonghui.svc.cluster.local	mysql-slave-0
```

所以为什么dns延迟会导致show slave status 一直处于connecting状态，而不会报任何错误(比如timeout)
