### ISSUE TITLE
scheduler-plugins 如何载入KubeSchedulerConfiguration资源对象

### ISSUE THREAD

**Issue by shenkonghui** [shenkonghui/issue#119]
调度器内部使用了crd，但是需要用的KubeSchedulerConfiguration的clientConnection.kubeconfig 作为kubeconfig文件

```
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  # kubeconfig: "REPLACE_ME_WITH_KUBE_CONFIG_PATH"
  kubeconfig: "/etc/kubernetes/scheduler.conf"
profiles:
- schedulerName: topo-aware-scheduler
  plugins:
    filter:
      enabled:
      - name: NodeResourceTopologyMatch
```

**Comment by shenkonghui** [comment]
kube-schedule是这样读取配置的

https://github.com/kubernetes/kubernetes/blob/c2b5237ccd9c0f1d600d3072634ca66cefdf272f/cmd/kube-scheduler/app/options/options.go#L287
```
func (o *Options) Config() (*schedulerappconfig.Config, error) {
...
	c := &schedulerappconfig.Config{}
	if err := o.ApplyTo(c); err != nil {
		return nil, err
	}
...
}
```

但是scheduler-plugins并没有提供方法读取这个conig

目前暂时本地从环境变量读，k8s里面读取sa

**Comment by shenkonghui** [comment]
目前看到获取clientConnection. kubeconfig属性，只能通过framework.Plugin提供的ClientSet()方法获取clientset，操作内置资源是没有问题的。

如果想要操作crd，还是需要定义一个pluginConfig字段
```
  pluginConfig:
  - name: Coscheduling
    args:
      permitWaitingTimeSeconds: 10
      deniedPGExpirationTimeSeconds: 3
      kubeConfigPath: "REPLACE_ME_WITH_KUBE_CONFIG_PATH"
```
https://github.com/kubernetes-sigs/scheduler-plugins/blob/v0.20.10/manifests/coscheduling/scheduler-config.yaml#L27

然后定义api结构
```
type CoschedulingArgs struct {
	metav1.TypeMeta `json:",inline"`

	// PermitWaitingTime is the wait timeout in seconds.
	PermitWaitingTimeSeconds *int64 `json:"permitWaitingTimeSeconds,omitempty"`
	// DeniedPGExpirationTimeSeconds is the expiration time of the denied podgroup store.
	DeniedPGExpirationTimeSeconds *int64 `json:"deniedPGExpirationTimeSeconds,omitempty"`
	// KubeMaster is the url of api-server
	KubeMaster *string `json:"kubeMaster,omitempty"`
	// KubeConfigPath for scheduler
	KubeConfigPath *string `json:"kubeConfigPath,omitempty"`
}
```
https://github.com/kubernetes-sigs/scheduler-plugins/blob/v0.20.10/pkg/apis/config/v1beta1/types.go#L28

最后再代码中获取该配置
```
args, ok := obj.(*config.CoschedulingArgs)
```
https://github.com/kubernetes-sigs/scheduler-plugins/blob/v0.20.10/pkg/coscheduling/coscheduling.go#L63

然后生成deepopy等方法，但是我没有测试成功...，为了偷懒直接用获取集群内部sa的方式了
