### ISSUE TITLE
twemproxy 只会代理第一个redis

### ISSUE THREAD

**Issue by shenkonghui** [shenkonghui/issue#127]
配置如下，配置了三个redis
```
alpha:
  listen: 127.0.0.1:6379
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  redis: true
  redis_auth: dangerous
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
   - 10.244.221.77:6379:1
   - 10.244.221.107:6379:1
   - 10.244.221.79:6379:1
```
所有的代理请求都在第一个redis上
