### ISSUE TITLE
容器中redis压测CPU只能到0.5

### ISSUE THREAD

**Issue by shenkonghui** [shenkonghui/issue#132]
```
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
```
通过redis-benchmark压测，发现CPU最高只有0.5
![image](https://user-images.githubusercontent.com/10442820/131968359-3e789b38-5247-496f-ad18-72ca53f24b16.png)
