### ISSUE TITLE
calico statefulset固定IP

### ISSUE THREAD

**Issue by shenkonghui** [shenkonghui/issue#171]
calico固定IP只支持一个pod，如果是stateulset多个pod，可以先划分ippol，设定相应的子网
```
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: new-pool1
spec:
  blockSize: 31
  cidr: 10.243.0.0/31
  ipipMode: Never
  natOutgoing: true
```
spec.template.metadata.annotations 进行配置
```
cni.projectcalico.org/ipv4pools: '["new-pool1"]'
```

*问题*
```
Warning  FailedCreatePodSandBox  4m1s                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "d4d65804e1ff8d905b0b4b96cb039c01f5bb4d3b826ee878dd89258b0502fd3e" network for pod "mysql-1": networkPlugin cni failed to set up pod "mysql-1_shenkonghui" network: error adding host side routes for interface: cali1bdb03374a0, error: route (Ifindex: 55, Dst: 10.243.0.1/32, Scope: 253) already exists for an interface other than 'cali1bdb03374a0'
```
登录机器删除路由即可
```
ip route del 10.243.0.1/32
```
