### ISSUE TITLE
istio: istio-proxy本来好的，突然全部not ready了

### ISSUE THREAD

**Issue by shenkonghui** [shenkonghui/issue#29]
## 描述
原来好的istio-proxy，突然全部503。

## 原因
默认情况下，istio-proxy将提取所有服务的配置，然后将其加载到envoy。 由于当前环境中的服务/端点数量众多，istio-proxy的性能会下降。

## 您可以看到当前集群中有2171个端点。
```
$ oc get ep --all-namespace | wc -l
2171
```
## 解决方法
当然，您可以增加istio-proxy资源来解决问题，主要是CPU需求。 经过测试，在当前规模下，CPU至少需要0.5core。

另一个解决方案是隔离名称空间。 应该有许多不经常访问其他名称空间的istio应用程序。 因此，您可以将Sidecar配置为隔离。 像这样。
```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: <your  namespace>
spec:
  egress:
  - hosts:
    - "./*"
    - "istio-system/*"
 ```
这是最小的配置。 它将仅提取当前名称空间和系统名称空间的配置，这可以满足大多数需求，并且对istio-proxy的性能影响最小。 如果要访问其他名称空间，只需在主机下添加“ {namesapce} / *”
