### ISSUE TITLE
metrics中增加前缀

### ISSUE THREAD

**Issue by shenkonghui** [shenkonghui/issue#42]
zookeeper默认的metrics没有带zk前缀

**Comment by shenkonghui** [comment]
可以那么写
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 1
  labels:
    app: {{ include "zookeeper.fullname" . }}
  name: {{ include "zookeeper.fullname" . }}
spec:
  endpoints:
    - interval: 30s
      port: tcp-metrics
      metricRelabelings:
      - sourceLabels: [__name__]
        replacement: zk_${1}
        targetLabel: __name__
  selector:
    matchLabels:
      app: {{ include "zookeeper.fullname" . }}
```
