### ISSUE TITLE
mysql提示 Client requested master to start replication from position > file           size'''

### ISSUE THREAD

**Issue by shenkonghui** [shenkonghui/issue#71]
在双主架构或者MGR架构的mysql中，当原本连接复制的mysql挂了以后，就无法连接新的mysql进行复制

**Comment by shenkonghui** [comment]
mgr的mysql0和mysql1 binlog相同如下
```
| mysql-bin.000003 | 819 | Query          | 1021445123 |         914 | CREATE DATABASE test                                              |
```

slave binlog如下
```
| mysql-bin.000003 | 968 | Query          | 1021445123 |        1063 | CREATE DATABASE test
```

slave状态如下
```
mysql> show slave status\G;
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: 10.96.198.209
                  Master_User: root
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File: mysql-bin.000003
          Read_Master_Log_Pos: 914
               Relay_Log_File: relay-replication_applier.000004
                Relay_Log_Pos: 1119
        Relay_Master_Log_File: mysql-bin.000003
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 914
              Relay_Log_Space: 1533
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: 0
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 1021655123
                  Master_UUID: 16c68120-be5f-11eb-8e65-7a0368874b49
             Master_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Slave has read all relay log; waiting for more updates
           Master_Retry_Count: 86400
                  Master_Bind:
      Last_IO_Error_Timestamp:
     Last_SQL_Error_Timestamp:
               Master_SSL_Crl:
           Master_SSL_Crlpath:
           Retrieved_Gtid_Set: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa:1-3
            Executed_Gtid_Set: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa:1-3,
e8efc50a-be5f-11eb-9664-d26a8b5f7329:1
                Auto_Position: 0
         Replicate_Rewrite_DB:
                 Channel_Name: replication_applier
           Master_TLS_Version:
```
