### ISSUE TITLE
mysql slave切换以后，访问service 迁移到另外一个实例，但是binlog不匹配 ： 'Could not find first log file name in binary log index file

### ISSUE THREAD

**Issue by shenkonghui** [shenkonghui/issue#73]
使用operator实现如下架构
![image](https://user-images.githubusercontent.com/10442820/120146089-1f4b5880-c217-11eb-90d2-f6c150e2f4cc.png)

slave的错误
```
mysql> show slave status\G;
*************************** 1. row ***************************
              Slave_IO_State:
                  Master_Host: 10.96.198.209
                  Master_User: root
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File: mysql-bin.000005
          Read_Master_Log_Pos: 838
               Relay_Log_File: relay-replication_applier.000008
                Relay_Log_Pos: 1043
        Relay_Master_Log_File: mysql-bin.000005
             Slave_IO_Running: No
            Slave_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 838
              Relay_Log_Space: 1454
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: NULL
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 1236
                Last_IO_Error: Got fatal error 1236 from master when reading data from binary log: 'Could not find first log file name in binary log index file'
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 1021865123
                  Master_UUID: 4fd1ab6d-be6c-11eb-82a0-da071f535483
             Master_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Slave has read all relay log; waiting for more updates
           Master_Retry_Count: 86400
                  Master_Bind:
      Last_IO_Error_Timestamp: 210527 05:55:46
     Last_SQL_Error_Timestamp:
               Master_SSL_Crl:
           Master_SSL_Crlpath:
           Retrieved_Gtid_Set: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa:1-6
            Executed_Gtid_Set: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa:1-6,
e8efc50a-be5f-11eb-9664-d26a8b5f7329:1
                Auto_Position: 0
         Replicate_Rewrite_DB:
                 Channel_Name: replication_applier
           Master_TLS_Version:
```

mgr mysql-0 binlog文件
```
mysql> show binary logs;
+------------------+-----------+
| Log_name         | File_size |
+------------------+-----------+
| mysql-bin.000001 |       169 |
| mysql-bin.000002 |       169 |
| mysql-bin.000003 |      2210 |
+------------------+-----------+
3 rows in set (0.00 sec)
```
mgr mysql-2 binlog文件
```
mysql> show binary logs;
+------------------+-----------+
| Log_name         | File_size |
+------------------+-----------+
| mysql-bin.000001 |       169 |
| mysql-bin.000002 |       169 |
| mysql-bin.000003 |      2210 |
+------------------+-----------+
3 rows in set (0.00 sec)
```
mgr mysql-1 binlog文件
```
mysql> show binary logs;
+------------------+-----------+
| Log_name         | File_size |
+------------------+-----------+
| mysql-bin.000001 |       169 |
| mysql-bin.000002 |       169 |
| mysql-bin.000003 |       933 |
| mysql-bin.000004 |       533 |
| mysql-bin.000005 |       857 |
| mysql-bin.000006 |       514 |
+------------------+-----------+
6 rows in set (0.00 sec)
```

的确之前连接的实例binlog到了06，和比其他两个实例多
