### ISSUE TITLE
k8s附属资源无法自动删除

### ISSUE THREAD

**Issue by shenkonghui** [shenkonghui/issue#81]
mysql operator中需要自动创建service，但是发现，删除cr对象后，service不会自动删除

实现代码
```
	service := &corev1.Service{
		ObjectMeta: metav1.ObjectMeta{
			Name:        svcName,
			Namespace:   crd.Namespace,
			Annotations: annotations,
			Labels:      crd.Spec.Statefulset.Labels,
			OwnerReferences: []metav1.OwnerReference{
				{
					APIVersion:         controllerKind.GroupVersion().Version,
					BlockOwnerDeletion: &trueVar,
					Controller:         &trueVar,
					Kind:               mysqlv1.MysqlClusterName,
					Name:               crd.Name,
					UID:                crd.UID,
				},
			},
		},
		Spec: corev1.ServiceSpec{
			Ports: []corev1.ServicePort{{
				Port:       serverPort,
				TargetPort: intstr.FromInt(int(serverPort)),
			}},
			Selector: crd.Spec.Statefulset.Labels,
		},
	}
```

```
operator.kubeClient.CoreV1().Services(service.Namespace).Create(service)
```

查看创建后的资源
```
apiVersion: v1
kind: Service
metadata:
  ownerReferences:
  - apiVersion: v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: MysqlCluster
    name: mysql
    uid: 80212a76-a36c-4458-bc56-71d2a113ceac
...
```
